kind: pipeline
name: plots
type: docker

steps:
  - name: export
    image: python:3
    commands:
      - python benchmark.py export > data.js

  - name: upload
    image: plugins/drone-sftp
    settings:
      host: 134.96.220.231
      port: 443
      username:
        from_secret: EGON_USERNAME
      password:
        from_secret: EGON_PASSWORD
      destination_path: /anyq
      files:
        - index.html
        - data.js

node:
  env: cguds-warrior
