kind: pipeline
name: plots
type: docker

steps:
  - name: export
    image: python:3
    commands:
      - python benchmark.py export --out baseline "benchmark-queue-concurrent--.*"
      - python benchmark.py export --out cuda-its "benchmark-(queue-concurrent)--.*-cuda" "benchmark-(queue-concurrent-its)--.*-cuda"

  - name: upload
    image: beeblebrox.cg.uni-saarland.de/alpine/drone-plugin-sftp
    settings:
      host: 134.96.220.231
      port: 443
      username:
        from_secret: EGON_USERNAME
      password:
        from_secret: EGON_PASSWORD
      destination_path: /anyq
      files:
        - baseline/index.html
        - baseline/main.js
        - baseline/*.json
        - cuda-its/index.html
        - cuda-its/main.js
        - cuda-its/*.json
    when:
      branch:
        - master
      event:
        - push

node:
  env: cguds-warrior

image_pull_secrets:
  - REGISTRY_AUTH_CREDENTIALS
