kind: pipeline
name: plots
type: docker

steps:
  - name: export
    image: python:3
    commands:
      - python benchmark.py export > data.js

  - name: upload
    image: cupcakearmy/drone-deploy
    settings:
      host: 134.96.220.231
      port: 443
      user:
        from_secret: EGON_USERNAME
      password:
        from_secret: EGON_PASSWORD
      target: /anyq
      sources:
        - index.html
        - data.js
      commands:
        - ls -al
        - ls -al /anyq

node:
  env: cguds-warrior
