include(${CMAKE_CURRENT_LIST_DIR}/BQ/queue.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/CPCQ/queue.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/MOQ/queue.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/MSQ/queue.cmake)

set(queue_types_cpu ConcurrentProducerConsumerQueue BrokerWorkDistributorQueue MichaelScottQueue MoodyCamelQueue)
set(queue_types_fiberless ConcurrentProducerConsumerQueue BrokerWorkDistributorQueue MichaelScottQueue MoodyCamelQueue)
set(queue_types_cuda ConcurrentProducerConsumerQueue BrokerWorkDistributorQueue MichaelScottQueue)
set(queue_types_nvvm ConcurrentProducerConsumerQueue BrokerWorkDistributorQueue MichaelScottQueue)
set(queue_types_amdgpu ConcurrentProducerConsumerQueue BrokerWorkDistributorQueue MichaelScottQueue)


function(get_queue_constructor var queue_type element_type)
	if (DEFINED ${queue_type}_constructor_${element_type})
		set(${var} ${${queue_type}_constructor_${element_type}} PARENT_SCOPE)
	else()
		if (DEFINED ${queue_type}_constructor)
			if ("${${queue_type}_constructor}" STREQUAL "")
				set(${var} "" PARENT_SCOPE)
			else()
				set(${var} "${${queue_type}_constructor}[${element_type}]" PARENT_SCOPE)
			endif()
		else()
			set(${var} "create${queue_type}[${element_type}]" PARENT_SCOPE)
		endif()
	endif()
endfunction()
